#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v5
# autospec commit: c02b2fe
#
Name     : libxkbcommon
Version  : 1.7.0
Release  : 40
URL      : https://xkbcommon.org/download/libxkbcommon-1.7.0.tar.xz
Source0  : https://xkbcommon.org/download/libxkbcommon-1.7.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : ICU
Requires: libxkbcommon-bin = %{version}-%{release}
Requires: libxkbcommon-data = %{version}-%{release}
Requires: libxkbcommon-lib = %{version}-%{release}
Requires: libxkbcommon-libexec = %{version}-%{release}
Requires: libxkbcommon-license = %{version}-%{release}
Requires: libxkbcommon-man = %{version}-%{release}
BuildRequires : bash-completion-dev
BuildRequires : bison
BuildRequires : buildreq-meson
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libX11-lib
BuildRequires : libX11-lib32
BuildRequires : pkgconfig(32icu-uc)
BuildRequires : pkgconfig(32libxml-2.0)
BuildRequires : pkgconfig(32xcb)
BuildRequires : pkgconfig(32xcb-xkb)
BuildRequires : pkgconfig(bash-completion)
BuildRequires : pkgconfig(icu-uc)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-xkb)
BuildRequires : pkgconfig(xkeyboard-config)
BuildRequires : valgrind
BuildRequires : wayland-dev
BuildRequires : wayland-dev32
BuildRequires : wayland-protocols-dev
BuildRequires : wayland-protocols-dev32
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: crashavoid.patch

%description
# libxkbcommon
libxkbcommon is a keyboard keymap compiler and support library which
processes a reduced subset of keymaps as defined by the [XKB] \(X Keyboard
Extension) specification.  It also contains a module for handling Compose
and dead keys and a separate library for listing available keyboard layouts.

%package bin
Summary: bin components for the libxkbcommon package.
Group: Binaries
Requires: libxkbcommon-data = %{version}-%{release}
Requires: libxkbcommon-libexec = %{version}-%{release}
Requires: libxkbcommon-license = %{version}-%{release}

%description bin
bin components for the libxkbcommon package.


%package data
Summary: data components for the libxkbcommon package.
Group: Data

%description data
data components for the libxkbcommon package.


%package dev
Summary: dev components for the libxkbcommon package.
Group: Development
Requires: libxkbcommon-lib = %{version}-%{release}
Requires: libxkbcommon-bin = %{version}-%{release}
Requires: libxkbcommon-data = %{version}-%{release}
Provides: libxkbcommon-devel = %{version}-%{release}
Requires: libxkbcommon = %{version}-%{release}

%description dev
dev components for the libxkbcommon package.


%package dev32
Summary: dev32 components for the libxkbcommon package.
Group: Default
Requires: libxkbcommon-lib32 = %{version}-%{release}
Requires: libxkbcommon-bin = %{version}-%{release}
Requires: libxkbcommon-data = %{version}-%{release}
Requires: libxkbcommon-dev = %{version}-%{release}

%description dev32
dev32 components for the libxkbcommon package.


%package lib
Summary: lib components for the libxkbcommon package.
Group: Libraries
Requires: libxkbcommon-data = %{version}-%{release}
Requires: libxkbcommon-libexec = %{version}-%{release}
Requires: libxkbcommon-license = %{version}-%{release}
Requires: xkeyboard-config-data

%description lib
lib components for the libxkbcommon package.


%package lib32
Summary: lib32 components for the libxkbcommon package.
Group: Default
Requires: libxkbcommon-data = %{version}-%{release}
Requires: libxkbcommon-license = %{version}-%{release}

%description lib32
lib32 components for the libxkbcommon package.


%package libexec
Summary: libexec components for the libxkbcommon package.
Group: Default
Requires: libxkbcommon-license = %{version}-%{release}

%description libexec
libexec components for the libxkbcommon package.


%package license
Summary: license components for the libxkbcommon package.
Group: Default

%description license
license components for the libxkbcommon package.


%package man
Summary: man components for the libxkbcommon package.
Group: Default

%description man
man components for the libxkbcommon package.


%prep
%setup -q -n libxkbcommon-1.7.0
cd %{_builddir}/libxkbcommon-1.7.0
%patch -P 1 -p1
pushd ..
cp -a libxkbcommon-1.7.0 build32
popd
pushd ..
cp -a libxkbcommon-1.7.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1711377963
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2
pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
ASFLAGS="${CLEAR_INTERMEDIATE_ASFLAGS}${CLEAR_INTERMEDIATE_ASFLAGS:+ }--32"
CFLAGS="${CLEAR_INTERMEDIATE_CFLAGS}${CLEAR_INTERMEDIATE_CFLAGS:+ }-m32 -mstackrealign"
CXXFLAGS="${CLEAR_INTERMEDIATE_CXXFLAGS}${CLEAR_INTERMEDIATE_CXXFLAGS:+ }-m32 -mstackrealign"
LDFLAGS="${CLEAR_INTERMEDIATE_LDFLAGS}${CLEAR_INTERMEDIATE_LDFLAGS:+ }-m32 -mstackrealign"
meson --libdir=lib32 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :
cd ../build32;
meson test -C builddir --print-errorlogs || : || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/libxkbcommon
cp %{_builddir}/libxkbcommon-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/libxkbcommon/3226d82e896c1428856ecbb68d3eb29cba7c4b19 || :
pushd ../build32/
DESTDIR=%{buildroot} ninja -C builddir install
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/xkbcli
/usr/bin/xkbcli

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/xkbcli

%files dev
%defattr(-,root,root,-)
/usr/include/xkbcommon/xkbcommon-compat.h
/usr/include/xkbcommon/xkbcommon-compose.h
/usr/include/xkbcommon/xkbcommon-keysyms.h
/usr/include/xkbcommon/xkbcommon-names.h
/usr/include/xkbcommon/xkbcommon-x11.h
/usr/include/xkbcommon/xkbcommon.h
/usr/include/xkbcommon/xkbregistry.h
/usr/lib64/libxkbcommon-x11.so
/usr/lib64/libxkbcommon.so
/usr/lib64/libxkbregistry.so
/usr/lib64/pkgconfig/xkbcommon-x11.pc
/usr/lib64/pkgconfig/xkbcommon.pc
/usr/lib64/pkgconfig/xkbregistry.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libxkbcommon-x11.so
/usr/lib32/libxkbcommon.so
/usr/lib32/libxkbregistry.so
/usr/lib32/pkgconfig/32xkbcommon-x11.pc
/usr/lib32/pkgconfig/32xkbcommon.pc
/usr/lib32/pkgconfig/32xkbregistry.pc
/usr/lib32/pkgconfig/xkbcommon-x11.pc
/usr/lib32/pkgconfig/xkbcommon.pc
/usr/lib32/pkgconfig/xkbregistry.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libxkbcommon-x11.so.0.0.0
/V3/usr/lib64/libxkbcommon.so.0.0.0
/V3/usr/lib64/libxkbregistry.so.0.0.0
/usr/lib64/libxkbcommon-x11.so.0
/usr/lib64/libxkbcommon-x11.so.0.0.0
/usr/lib64/libxkbcommon.so.0
/usr/lib64/libxkbcommon.so.0.0.0
/usr/lib64/libxkbregistry.so.0
/usr/lib64/libxkbregistry.so.0.0.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libxkbcommon-x11.so.0
/usr/lib32/libxkbcommon-x11.so.0.0.0
/usr/lib32/libxkbcommon.so.0
/usr/lib32/libxkbcommon.so.0.0.0
/usr/lib32/libxkbregistry.so.0
/usr/lib32/libxkbregistry.so.0.0.0

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/xkbcommon/xkbcli-compile-compose
/V3/usr/libexec/xkbcommon/xkbcli-compile-keymap
/V3/usr/libexec/xkbcommon/xkbcli-how-to-type
/V3/usr/libexec/xkbcommon/xkbcli-interactive-evdev
/V3/usr/libexec/xkbcommon/xkbcli-interactive-wayland
/V3/usr/libexec/xkbcommon/xkbcli-interactive-x11
/V3/usr/libexec/xkbcommon/xkbcli-list
/usr/libexec/xkbcommon/xkbcli-compile-compose
/usr/libexec/xkbcommon/xkbcli-compile-keymap
/usr/libexec/xkbcommon/xkbcli-how-to-type
/usr/libexec/xkbcommon/xkbcli-interactive-evdev
/usr/libexec/xkbcommon/xkbcli-interactive-wayland
/usr/libexec/xkbcommon/xkbcli-interactive-x11
/usr/libexec/xkbcommon/xkbcli-list

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libxkbcommon/3226d82e896c1428856ecbb68d3eb29cba7c4b19

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xkbcli-compile-compose.1
/usr/share/man/man1/xkbcli-compile-keymap.1
/usr/share/man/man1/xkbcli-how-to-type.1
/usr/share/man/man1/xkbcli-interactive-evdev.1
/usr/share/man/man1/xkbcli-interactive-wayland.1
/usr/share/man/man1/xkbcli-interactive-x11.1
/usr/share/man/man1/xkbcli-list.1
/usr/share/man/man1/xkbcli.1
