#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libxkbcommon
Version  : 0.6.1
Release  : 4
URL      : http://xkbcommon.org/download/libxkbcommon-0.6.1.tar.xz
Source0  : http://xkbcommon.org/download/libxkbcommon-0.6.1.tar.xz
Summary  : XKB API common to servers and clients
Group    : Development/Tools
License  : MIT
Requires: libxkbcommon-lib
Requires: libxkbcommon-doc
BuildRequires : bison
BuildRequires : doxygen
BuildRequires : graphviz
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-xkb)
BuildRequires : pkgconfig(xkeyboard-config)
BuildRequires : pkgconfig(xorg-macros)

%description
# libxkbcommon
libxkbcommon is a keyboard keymap compiler and support library which
processes a reduced subset of keymaps as defined by the XKB (X Keyboard
Extension) specification.  It also contains a module for handling Compose
and dead keys.

%package dev
Summary: dev components for the libxkbcommon package.
Group: Development
Requires: libxkbcommon-lib
Provides: libxkbcommon-devel

%description dev
dev components for the libxkbcommon package.


%package doc
Summary: doc components for the libxkbcommon package.
Group: Documentation

%description doc
doc components for the libxkbcommon package.


%package lib
Summary: lib components for the libxkbcommon package.
Group: Libraries

%description lib
lib components for the libxkbcommon package.


%prep
%setup -q -n libxkbcommon-0.6.1

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/xkbcommon/xkbcommon-compat.h
/usr/include/xkbcommon/xkbcommon-compose.h
/usr/include/xkbcommon/xkbcommon-keysyms.h
/usr/include/xkbcommon/xkbcommon-names.h
/usr/include/xkbcommon/xkbcommon-x11.h
/usr/include/xkbcommon/xkbcommon.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libxkbcommon/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
