#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libxkbcommon
Version  : 0.8.1
Release  : 14
URL      : http://xkbcommon.org/download/libxkbcommon-0.8.1.tar.xz
Source0  : http://xkbcommon.org/download/libxkbcommon-0.8.1.tar.xz
Summary  : XKB API common to servers and clients - X11 support
Group    : Development/Tools
License  : ICU
Requires: libxkbcommon-lib
Requires: libxkbcommon-license
BuildRequires : bison
BuildRequires : buildreq-meson
BuildRequires : doxygen
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : graphviz
BuildRequires : pkg-config
BuildRequires : pkgconfig(32xcb)
BuildRequires : pkgconfig(32xcb-xkb)
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-xkb)
BuildRequires : pkgconfig(xkeyboard-config)
BuildRequires : pkgconfig(xorg-macros)

%description
# libxkbcommon
libxkbcommon is a keyboard keymap compiler and support library which
processes a reduced subset of keymaps as defined by the XKB (X Keyboard
Extension) specification.  It also contains a module for handling Compose
and dead keys.

%package dev
Summary: dev components for the libxkbcommon package.
Group: Development
Requires: libxkbcommon-lib
Provides: libxkbcommon-devel

%description dev
dev components for the libxkbcommon package.


%package dev32
Summary: dev32 components for the libxkbcommon package.
Group: Default
Requires: libxkbcommon-lib32
Requires: libxkbcommon-dev

%description dev32
dev32 components for the libxkbcommon package.


%package doc
Summary: doc components for the libxkbcommon package.
Group: Documentation

%description doc
doc components for the libxkbcommon package.


%package lib
Summary: lib components for the libxkbcommon package.
Group: Libraries
Requires: libxkbcommon-license

%description lib
lib components for the libxkbcommon package.


%package lib32
Summary: lib32 components for the libxkbcommon package.
Group: Default
Requires: libxkbcommon-license

%description lib32
lib32 components for the libxkbcommon package.


%package license
Summary: license components for the libxkbcommon package.
Group: Default

%description license
license components for the libxkbcommon package.


%prep
%setup -q -n libxkbcommon-0.8.1
pushd ..
cp -a libxkbcommon-0.8.1 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533310163
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1533310163
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libxkbcommon
cp LICENSE %{buildroot}/usr/share/doc/libxkbcommon/LICENSE
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/xkbcommon/xkbcommon-compat.h
/usr/include/xkbcommon/xkbcommon-compose.h
/usr/include/xkbcommon/xkbcommon-keysyms.h
/usr/include/xkbcommon/xkbcommon-names.h
/usr/include/xkbcommon/xkbcommon-x11.h
/usr/include/xkbcommon/xkbcommon.h
/usr/lib64/libxkbcommon-x11.so
/usr/lib64/libxkbcommon.so
/usr/lib64/pkgconfig/xkbcommon-x11.pc
/usr/lib64/pkgconfig/xkbcommon.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libxkbcommon-x11.so
/usr/lib32/libxkbcommon.so
/usr/lib32/pkgconfig/32xkbcommon-x11.pc
/usr/lib32/pkgconfig/32xkbcommon.pc
/usr/lib32/pkgconfig/xkbcommon-x11.pc
/usr/lib32/pkgconfig/xkbcommon.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libxkbcommon/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxkbcommon-x11.so.0
/usr/lib64/libxkbcommon-x11.so.0.0.0
/usr/lib64/libxkbcommon.so.0
/usr/lib64/libxkbcommon.so.0.0.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libxkbcommon-x11.so.0
/usr/lib32/libxkbcommon-x11.so.0.0.0
/usr/lib32/libxkbcommon.so.0
/usr/lib32/libxkbcommon.so.0.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/libxkbcommon/LICENSE
